### ISSUE TITLE
Speaker icon overshadows the icon of open tab

### ISSUE THREAD

**Issue by greeid** [UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox#8]
![selected_07_28_15:50:33](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/assets/58597122/738b4321-f246-4ef4-a79b-dd75ecb480df)
![Jul-28_15:52:08](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/assets/58597122/2a9babd4-cda8-4bb4-b7ec-5cd6f358c1ab)

**Comment by greeid** [comment]
Have been using FlyingFox till recently and just moved to it...
But the speaker overshadows the youtube icon or any icon in that matter if it's playing sound...

**Comment by UnlimitedAvailableUsername** [comment]
It's actually a feature, since Edge also does this and I've decided to replicate it. If you don't want the speaker icon overlay, you can remove it:

- Go to Tree Style Tab Options and in to Advanced > Extra Style Rules (where you copy-pasted the css style)
- Go to the part of the code responsible for Hover tabs layout:
`/************************
Hover-over sidebar layout
************************/
`

- Then scroll down a bit, and remove these lines:

`tab-item tab-sound-button {
  	height: var(--tab-sound-button-background-size) !important;
  	min-width: var(--tab-item-substance-height) !important;
    margin-left: -2.65em !important;
    opacity: 1.0;
    background: var(--tab-surface-active);
  }
  tab-item tab-sound-button::before {
    border-radius: var(--tab-border-radius-size) !important;
  }`

Screenshot of where it is located:
![Screenshot 2023-07-29 112748](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/assets/81744148/6b32fcff-7f03-48a1-8824-7f11b95f3390)

This should remove the sound icon from overlaying the current tab icon.

**Comment by greeid** [comment]
sorry for not making it more clear, I love the little sound overlay to mute tabs and don't want to remove it  but make it smaller only

**Comment by UnlimitedAvailableUsername** [comment]
I see, if that's the case, then you could just modify the value on `--tab-button-icon-size` (as can be seen on the screenshot) and the `margin-left` inside the `tab-item tab-sound-button`.

or Additionally if you just want it to look smaller and on the top-right corner, you could do this:

- Still, inside the `/************************ Hover-over sidebar layout ************************/ ` go to and remove the `:root {
    --tab-sound-button-background-size: 32px;
    --tab-sound-button-icon-size: 24px;
  }` and the whole `tab-item tab-sound-button-before`
- Afterwards, replace the whole `:tab-item tab-sound-button` snippet with this code:
`tab-item tab-sound-button {
    height: var(--tab-sound-button-background-size);
    width: var(--tab-sound-button-background-size);
    border-radius: 100%;
    opacity: 1.0;
    margin: -1em -1.5em 0em !important;
  }`
![Screenshot 2023-07-29 112748](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/assets/81744148/f3ff1fba-19d0-4390-bbf2-8de1c2c38325)

The result will then look like this:

  
![Screenshot 2023-07-29 132011](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox/assets/81744148/224719b3-f2bb-4137-b62c-fdca5904c158)

**Comment by greeid** [comment]
Themks
